services:
  - type: web
    name: email-writer-backend
    env: java
    buildCommand: "mvn clean install -DskipTests"
    startCommand: "java -jar target/email-writer-0.0.1-SNAPSHOT.jar"
    instanceType: free